Back-End/2023-09-19/work/source/python/Django/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('write/', views.write_article, name='write_article'),
    path('add/', views.add, name='add_article'),
    path('<int:article_id>/', views.view, name='view_article'),
    path('update/<int:article_id>/', views.update, name='update_article'),
    path('delete/<int:article_id>/', views.delete, name='delete_article'),
]

Back-End/2023-09-19/work/source/python/Django/sku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

Back-End/2023-09-19/work/source/python/Django/board/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    write_date = models.DateTimeField(default=now, editable=False)
    write_id = models.CharField(max_length=50)

    def __str__(self):
        return self.title

Back-End/2023-09-19/work/source/python/Django/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Notice
from django.urls import reverse
from django.utils import timezone

# Create your views here.
def index(request):
    article_list = Notice.objects.all().order_by('-write_date') # -? desc
    context = {'article_list': article_list}
    return render(request, 'board/index.html', context)

def write_article(request):
    return render(request, 'board/write.html')

def add(request):
    notice = Notice()
    notice.title = request.POST['i_title']
    notice.content = request.POST['i_content']
    notice.write_id = 'Hi'
    notice.save()
    return redirect(reverse('board:index'))

def view(request, article_id):
    notice = get_object_or_404(Notice, pk=article_id)
    return render(request, 'board/view.html', {'article': notice})

def update(request, article_id):
    notice = Notice.objects.get(id=article_id)  # 업데이트는 글이 없는 경우가 없음
    if request.method == 'POST':
        notice.title = request.POST['title']
        notice.content = request.POST['content']
        notice.write_date = timezone.datetime.now()
        notice.save()
        return redirect(reverse('board:view_article', args=(article_id,)))
    else:
        return render(request, 'board/view.html', {'article': notice})
    
def delete(request, article_id):
    notice = Notice.objects.get(id=article_id)
    notice.delete()
    return redirect(reverse('board:index'))

Back-End/2023-09-19/work/source/python/Django/templates/board/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>글 목록</title>
    <style>
      .cls2 {
        text-align: center;
        font-size: 30px;
        display: block;
      }

      .cls1 {
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <table align="center" border="1" width="80%">
      <thead>
        <tr height="10" align="center" bgcolor="lightgreen">
          <th>글 번호</th>
          <th>작성자</th>
          <th>제목</th>
          <th>작성일</th>
        </tr>
      </thead>
      {% if not article_list %}
      <tbody>
        <tr height="10">
          <td colspan="4">
            <p align="center">
              <b>
                <span style="font-size: 20pt"> 등록된 글이 없습니다. </span>
              </b>
            </p>
          </td>
        </tr>
      </tbody>
      {% else %}
      <tbody>
        {% for article in article_list %}
        <tr align="center">
          <td width="5%">{{forloop.counter}}</td>
          <td width="10%">{{article.write_id}}</td>
          <td align="left" width="35%">
            <span style="padding-right: 30px"></span>
            <a class="cls1" href="{% url 'board:view_article' article.id %}">
              {{article.title}}
            </a>
          </td>
          <td width="10%">{{article.write_date}}</td>
        </tr>
        {% endfor %}
      </tbody>
      {% endif %}
    </table>
    <a href="{% url 'board:write_article' %}" class="cls1">
      <span class="cls2">글쓰기</span>
    </a>
  </body>
</html>

Back-End/2023-09-19/work/source/python/Django/templates/board/view.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>상세 조회</title>
    <style>
      #tr_btn_modify {
        display: none;
      }
    </style>
    <script>
      function backToList(frm) {
        frm.action = "{% url 'board:index' %}";
        frm.submit();
      }

      function fn_enable() {
        document.querySelector("#i_title").disabled = false;
        document.querySelector("#i_content").disabled = false;
        document.querySelector("#tr_btn").style.display = "none";
        document.querySelector("#tr_btn_modify").style.display = "table-row";
      }

      function fn_modify_article(frm) {
        frm.action = "{% url 'board:update_article' article.id %}";
        frm.submit();
      }

      function fn_remove_article(frm) {
        frm.action = "{% url 'board:delete_article' article.id %}";
        frm.submit();
      }
    </script>
  </head>
  <body>
    <form name="articleForm" method="post">
      {% csrf_token %}
      <table border="0" align="center">
        <tbody>
          <tr>
            <td width="150" align="center" bgcolor="#FF993">글 번호</td>
            <td>
              <input type="text" value="{{article.id}}" disabled />
              <!-- disabled 값 넘기기 용도 -->
              <input type="hidden" value="{{article.id}}" name="articleNo" />
            </td>
          </tr>
          <tr>
            <td width="150" align="center" bgcolor="#FF993">작성자</td>
            <td>
              <input
                type="text"
                value="{{article.write_id}}"
                name="writer"
                disabled
              />
            </td>
          </tr>
          <tr>
            <td width="150" align="center" bgcolor="#FF993">제목</td>
            <td>
              <input
                type="text"
                value="{{article.title}}"
                name="title"
                id="i_title"
                disabled
              />
            </td>
          </tr>
          <tr>
            <td width="150" align="center" bgcolor="#FF993">내용</td>
            <td>
              <textarea
                rows="20"
                cols="60"
                name="content"
                id="i_content"
                disabled
              >
{{article.content}}</textarea
              >
            </td>
          </tr>
          <tr>
            <td width="20" align="center" bgcolor="#FF993">작성일</td>
            <td>
              <input type="text" value="{{article.write_date}}" disabled />
            </td>
          </tr>
          <tr id="tr_btn">
            <td colspan="2" align="center">
              <input type="button" value="수정" onclick="fn_enable()" />
              <input
                type="button"
                value="삭제"
                onclick="fn_remove_article(articleForm)"
              />
              <input
                type="button"
                value="목록"
                onclick="backToList(articleForm)"
              />
            </td>
          </tr>
          <tr id="tr_btn_modify">
            <td colspan="2" align="center">
              <input
                type="button"
                value="저장"
                onclick="fn_modify_article(articleForm)"
              />
              <input
                type="button"
                value="취소"
                onclick="backToList(articleForm)"
              />
            </td>
          </tr>
        </tbody>
      </table>
    </form>
  </body>
</html>

Back-End/2023-09-19/work/source/python/Django/templates/board/write.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>글쓰기</title>
    <style>
      .class-caption {
        width: 100px;
      }

      .class-content {
        width: 500px;
      }
    </style>
    <script>
      function backToList(frm) {
        frm.action = "{% url 'board:index' %}";
        frm.submit();
      }
    </script>
  </head>
  <body>
    <h1 style="text-align: center">글쓰기</h1>
    <form
      name="articleForm"
      method="post"
      action="{% url 'board:add_article' %}"
    >
      {% csrf_token %}
      <table border="0" align="center">
        <tbody>
          <tr>
            <td align="right" class="class-caption">글 제목</td>
            <td colspan="2">
              <input
                type="text"
                maxlength="100"
                name="i_title"
                class="class-content"
              />
            </td>
          </tr>
          <tr>
            <td align="right" valign="top" class="class-caption">
              <br />글 내용:
            </td>
            <td colspan="2">
              <textarea
                name="i_content"
                rows="10"
                maxlength="2000"
                class="class-content"
              ></textarea>
            </td>
          </tr>
          <tr>
            <td align="right"></td>
            <td colspan="2">
              <input type="submit" value="저장" />
              <input
                type="button"
                value="목록"
                onclick="backToList(articleForm)"
              />
            </td>
          </tr>
        </tbody>
      </table>
    </form>
  </body>
</html>